name = "maria-havens-worker"
compatibility_date = "2025-10-08"
account_id = "be7b8ec33190c5f7e431eef2ee03eb0f"

[pages]
build_output_dir = "./dist"
functions_dir = "./src/functions"

[[d1_databases]]
binding = "DB"
database_name = "maria-havens"
database_id = "9f0b5394-58ef-4c76-9d41-6f123d08da29"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "0199c326-ff38-7723-a41d-ac28fbe57801"
